config/routes.rb
Rails.application.routes.draw do
  resources :clients
  get 'home/index'
  get 'home/ping'
  get 'home/add'
  get 'home/remove'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  after_commit :ping

  def ping
    require 'socket'

    client_socket = UDPSocket.new
    client_socket.connect("", 6001)
    client_socket.puts "ping"
    reply, from = client_socket.recvfrom( 20, 0 )
    puts reply
    client_socket.close	
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index

#  @clients = Client.all

    require 'json'
    f = File.read('config.json')
    @c = JSON.parse(f)
    @m = JSON.parse(f)['port_password']
    @c2=[]
 #@m.to_a do |v,k|
 #   @c2 << Client.find_by_port(v)
 #end

  @clients = Client.all

#  @clients = Client.find_by_port(@json_data)
#  @new_users = json_data.each do |key,value|
#    @clients << Client.find_by_port(value)
    #Client.create(:port => key, :password => value)
#  end
    
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save

      `echo 'add: {"server_port": #{@client.port}, "password":#{@client.password} }' | socat -t 0 - UDP:127.0.0.1:6001`

        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    `echo 'remove: {"server_port": #{@client.port} }' | socat -t 0 - UDP:127.0.0.1:6001`
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :port, :password, :st, :ldate, :ndate, :cash, :ver, :device, :mac, :ip, :desc)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def add(port, pass)
    #echo 'add: {"server_port": #{port}, "password":#{pass} }' | socat -t 0 - UDP:127.0.0.1:6001

    require 'json'
    file = File.read('config.json')
    @config = JSON.parse(file)
    @json_data = JSON.parse(file)['port_password']
    @new_users = json_data.each do |key,value|
      puts Client.find_by_port(key)
      #Client.create(:port => key, :password => value)
    end

  end

  def del(port)
#     `echo 'remove: {"server_port": #{port} }' | socat -t 0 - UDP:127.0.0.1:6001`
  end


    def ping
      @res= `echo 'ping' | socat -t 0 - UDP:127.0.0.1:6001`
#      require 'socket'
#      client_socket = UDPSocket.new
#      client_socket.connect("", 6001)
#      client_socket.puts "ping"
#      reply, from = client_socket.recvfrom( 20, 0 )
#      @reply=reply
#      puts reply
#      client_socket.close
    end

  def index(file='config.json')

  require 'json'
  @file = File.read(file)
  @clients = JSON.parse(@file)['port_password']
  @new_users = @clients.each do |key,value|
    if Client.find_by_port(key) then
      puts "true"
      @cls << Client.find_by_port("8388")
    else
      Client.create(:port => key, :password => value)
    end
  end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :client_name %>
  </div>

  <div class="field">
    <%= form.label :port %>
    <%= form.number_field :port, id: :client_port %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :client_password %>
  </div>

  <div class="field">
    <%= form.label :st %>
    <%= form.check_box :st, id: :client_st %>
  </div>

  <div class="field">
    <%= form.label :ldate %>
    <%= form.date_select :ldate, id: :client_ldate %>
  </div>

  <div class="field">
    <%= form.label :ndate %>
    <%= form.date_select :ndate, id: :client_ndate %>
  </div>

  <div class="field">
    <%= form.label :cash %>
    <%= form.number_field :cash, id: :client_cash %>
  </div>

  <div class="field">
    <%= form.label :ver %>
    <%= form.text_field :ver, id: :client_ver %>
  </div>

  <div class="field">
    <%= form.label :device %>
    <%= form.text_field :device, id: :client_device %>
  </div>

  <div class="field">
    <%= form.label :mac %>
    <%= form.text_field :mac, id: :client_mac %>
  </div>

  <div class="field">
    <%= form.label :ip %>
    <%= form.text_field :ip, id: :client_ip %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_field :desc, id: :client_desc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Port</th>
      <th>Password</th>
      <th>St</th>
      <th>Ldate</th>
      <th>Ndate</th>
      <th>Cash</th>
      <th>Ver</th>
      <th>Device</th>
      <th>Mac</th>
      <th>Ip</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.port %></td>
        <td><%= client.password %></td>
        <td><%= client.st %></td>
        <td><%= client.ldate %></td>
        <td><%= client.ndate %></td>
        <td><%= client.cash %></td>
        <td><%= client.ver %></td>
        <td><%= client.device %></td>
        <td><%= client.mac %></td>
        <td><%= client.ip %></td>
        <td><%= client.desc %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>
<%= link_to 'Sync', '/home/index'  %>

<%- @m.to_a.each do |k,v| %>
 <%= k %>
<% end %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Port:</strong>
  <%= @client.port %>
</p>

<p>
  <strong>Password:</strong>
  <%= @client.password %>
</p>

<p>
  <strong>St:</strong>
  <%= @client.st %>
</p>

<p>
  <strong>Ldate:</strong>
  <%= @client.ldate %>
</p>

<p>
  <strong>Ndate:</strong>
  <%= @client.ndate %>
</p>

<p>
  <strong>Cash:</strong>
  <%= @client.cash %>
</p>

<p>
  <strong>Ver:</strong>
  <%= @client.ver %>
</p>

<p>
  <strong>Device:</strong>
  <%= @client.device %>
</p>

<p>
  <strong>Mac:</strong>
  <%= @client.mac %>
</p>

<p>
  <strong>Ip:</strong>
  <%= @client.ip %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @client.desc %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/home/add.html.erb
<div id="vue"></div>
<%= link_to "Ping", home_ping_url %>
<pre>
<code>
<%= @file %>
</code>
</pre>

app/views/home/index.html.erb
<div id="vue"></div>

<%= link_to "Ping", home_ping_url %>
<pre>
<code>
<%= @file %>
</code>
</pre>

<%= @clients %>

app/views/home/ping.html.erb
<div id="vue"></div>
<%= link_to "Index", home_index_url %>
<pre>
<code>
<%= @res %>
</code>
</pre>

app/views/home/remove.html.erb
<div id="vue"></div>
<%= link_to "Ping", home_ping_url %>
<pre>
<code>
<%= @file %>
</code>
</pre>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sspro</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
    <div id="vue"></div>
    <% console %>

  </body>
</html>